import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  const { locale, locales } = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>B: redirect here</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {locale === "nb-no" ? (
          <h1 className={styles.title}>
            B: du burde vært her. <br /> <small>dette er hjemmesiden</small>
          </h1>
        ) : (
          <h1 className={styles.title}>
            B: redirect here <small>this is home</small>
          </h1>
        )}

        <p className={styles.description}>current locale is {locale}</p>
        <pre>{JSON.stringify(locales)}</pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
